name: KJDeathChestGUI
version: 1.0.0
main: xyz.kaijiieow.deathchest.plugin.DeathChestPlugin
api-version: 1.21
author: Kaijiieow
depend: [CoinsEngine, Vault, FancyHolograms]
commands:
  buyback:
    description: เปิด GUI เพื่อซื้อของที่หายคืน
    usage: /buyback
  tpchest:
    description: วาร์ปไปยังกล่องศพของตัวเอง
    usage: /tpchest
    permission: deathchest.tp
  dctp:
    description: (Admin) เปิด GUI เพื่อวาร์ปไปกล่องศพของผู้เล่น
    usage: /dctp <player>
    permission: deathchest.admin.tp
